name: Github Actions
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up
      uses: actions/setup-java@v2
      with: 
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --no-transfer-progress --batch-mode --update-snapshots verify
