name: Github Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up
      uses: actions/setup-java@v2
      with: 
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --no-transfer-progress --batch-mode --update-snapshots verify
